export class Quote {
  quoteId: string;
  quoteCode: string;
  quoteName: string;
  quoteDate: Date;
  sendQuoteDate: Date;
  seller: string;
  effectiveQuoteDate: number;
  expirationDate: Date;
  description: string;
  note: string;
  objectTypeId: string;
  objectType: string;
  customerName: string;
  customerContactId: string;
  paymentMethod: string;
  discountType: boolean;
  bankAccountId: string;
  daysAreOwed: number;
  maxDebt: number;
  receivedDate: Date;
  receivedHour: Date;
  intendedQuoteDate: Date;  //Ngày dự kiến báo giá
  recipientName: string;
  locationOfShipment: string;
  shippingNote: string;
  recipientPhone: string;
  recipientEmail: string;
  placeOfDelivery: string;
  amount: number;
  discountValue: number;
  statusId: string;
  active: boolean;
  createdById: string;
  createdDate: Date;
  updatedById: string;
  updatedDate: Date;
  personInChargeId: string;
  isSendQuote: boolean; 
  leadId: string; 
  saleBiddingId: string;
  approvalStep: number;
  investmentFundId: string;
  vat: number;
  percentAdvance: number;
  percentAdvanceType: any;
  constructionTime: any;
  createdByEmp: string;

  constructor() {
    this.quoteId = '00000000-0000-0000-0000-000000000000';
    this.quoteCode = null;
    this.quoteName = null;
    this.quoteDate = new Date();
    this.sendQuoteDate = null;
    this.seller = JSON.parse(localStorage.getItem('auth')).UserId;
    this.effectiveQuoteDate = 30;
    this.expirationDate = null;
    this.description = null;
    this.note = null;
    this.objectTypeId = '00000000-0000-0000-0000-000000000000';
    this.objectType = null;
    this.customerName = null;
    this.customerContactId = null;
    this.paymentMethod = '00000000-0000-0000-0000-000000000000';
    this.discountType = true;
    this.bankAccountId = null;
    this.daysAreOwed = 0;
    this.maxDebt = 0;
    this.receivedDate = new Date();
    this.receivedHour = null;
    this.intendedQuoteDate = new Date();
    this.recipientName = null;
    this.locationOfShipment = null;
    this.shippingNote = null;
    this.recipientPhone = null;
    this.recipientEmail = null;
    this.placeOfDelivery = null;
    this.amount = 0;
    this.discountValue = 0;
    this.statusId = null;
    this.active = true;
    this.createdById = JSON.parse(localStorage.getItem('auth')).UserId;
    this.createdDate = new Date();
    this.updatedById = JSON.parse(localStorage.getItem('auth')).UserId;
    this.updatedDate = new Date();
    this.personInChargeId = null;
    this.isSendQuote = false; 
    this.leadId = null; 
    this.saleBiddingId = null;
    this.approvalStep = null;
    this.investmentFundId = null;
    this.vat = 0;
    this.percentAdvance = 0;
  }
}
